### PR TITLE
feature: vite

### PR DESCRIPTION
**Pull request by marlonmarcello**
## Goal
This PR migrates the library to use the new Vite setup which will hopefully fix the issues our client is having with CommonJS exports.

I also took the liberty to complete the missing JSDocs and do some tweaks to the README that were wrong.

### CODE REVIEW

**Comment by andrewrubin** [comment]
Love it, looks great. I think we should establish a standard for using `.js` vs. `.jsx`, and when to do so. I vote JS, but only because that's what I'm used to. Any strong opinions there @marlonmarcello?

**Comment by andrewrubin** [comment]
Actually, spoke too soon. I think we need to remove the SCSS compilation for this particular repo

Screen Shot 2023-05-19 at 11 16 44

**Comment by marlonmarcello** [comment]
> Actually, I think we need to remove the SCSS compilation for this particular repo
> 
> Screen Shot 2023-05-19 at 11 16 44

My bad, I thought that it would just simply ignore it if there were no files.

**Comment by marlonmarcello** [comment]
> Love it, looks great. I think we should establish a standard for using `.js` vs. `.jsx`, and when to do so. I vote JS, but only because that's what I'm used to. Any strong opinions there @marlonmarcello?

Vite requires you to use `jsx` if a file has any JSX in it. Which makes sense, JSX is not JS if you think about it, It's a file that needs to be transpiled to work.  

I don't have an strong opinion but I feel like that thinking makes sense and it also makes it easy to spot files that have JSX from those that are just regular JS. How do you feel about that?

**Comment by andrewrubin** [comment]
@marlonmarcello this one looks good to me — I think we should bump it to `1.0.0-beta.0` and publish a beta version so we can test before making the proper 1.0.0 release — thoughts?

**Comment by marlonmarcello** [comment]
> @marlonmarcello this one looks good to me — I think we should bump it to `1.0.0-beta.0` and publish a beta version so we can test before making the proper 1.0.0 release — thoughts?

Great idea 💡

**Comment by marlonmarcello** [comment]
Done!

**Pull request merged**
